name: seashore_streets
channels:
  - conda-forge
  - defaults
  - udst
dependencies:
  - rasterstats=0.14.0
  - jupyter
  - rasterio=1.1.3
  - scikit-learn=0.22.2.post1
  - momepy=0.1.1
  - pandas=1.0.3
  - geopandas=0.7.0
  - osmnx=0.11.4
  - seaborn=0.10.0
  - jupyterlab
  - matplotlib
  - scipy=1.4.1
  - libpysal=4.2.2
  - pip:
    - husl==4.0.3
    - inequality==1.0.0
